apiVersion: v1
name: elasticsearch-storage
description: elasticsearch-storage chart that runs on kubernetes
version: 1.0.0
keywords:
  - elasticsearch-storage
  - kubernetes
home: https://github.com/stakater/chart-elasticsearch
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
