---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}-pv
  spec:
    capacity:
      storage: {{ .Values.elasticSearchStorage.capacity }}
    accessModes:
      - ReadWriteOnce
    nfs:
      # Create this first!
      server: {{ .Values.elasticSearchStorage.efs.server }}
      path: "/es-logging-data"
