---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.elasticSearchStorage.capacity }}
    volumeName: {{ template "name" . }}-pv