---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
    name: es-logging-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.elasticSearchStorage.capacity }}
    volumeName: es-logging-data-efs-pv