apiVersion: v1
name: elasticsearch
description: elasticsearch chart that runs on kubernetes
version: 1.0.3
keywords:
  - elasticsearch
  - kubernetes
home: https://github.com/stakater-charts/elasticsearch
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
