---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
    name: elasticsearch
  spec:
    ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
    selector:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
    name: elasticsearch-masters
  spec:
    clusterIP: None
    ports:
    - name: discovery
      port: 9300
      protocol: TCP
      targetPort: 9300
    selector:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
